config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # route for home page
  root 'users#index'

  resources :foods, only: [:index, :new, :create, :destroy]

  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  
  resources :public_recipes, only: [:index]

  resources :shopping_list, only: [:index]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { in: 1..50 }
  validates :preparation_time, presence: true, length: { in: 1..100 }
  validates :cooking_time, presence: true, length: { in: 1..100 }
  validates :description, presence: true, length: { in: 1..300 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    redirect_to recipes_path, flash: { alert: 'Please sign up or login!' } unless current_user

    @recipe = Recipe.new
  end

  def create
    @new_recipe = current_user.recipes.new(recipe_params)
    if @new_recipe.save!
      redirect_to recipes_path, flash: { alert: 'Your recipe is saved' }
    else
      redirect_to new_recipe_path, flash: { alert: 'Could not save your recipe' }
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy!
    flash[:notice] = 'You have deleted the food!'
    redirect_to recipes_path
  end

  def update
    if current_user

      @recipe = Recipe.find(params[:id])
      if @recipe.public
        @recipe.update(public: false)
        flash[:notice] = 'You have updated the recipe status to private'
      else
        @recipe.update(public: true)
        flash[:notice] = 'You have updated the recipe status to public'
      end
      redirect_to recipe_path
    else
      redirect_to recipe_path(params[:id]), flash: { alert: 'Please sign up or login!' }
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div class="recips-c">
  <h3 class="recipes-h3">All Recipes</h3>
  <div class="d-flex justify-content-end m-3">
    <button class='food-new-btn'>
      <%= link_to 'Add new recipe', new_recipe_path, class: "recipe-new-btn-t" %>
    </button> 
  </div>

  
  <div class="recipes-col">
    <% @recipes.each do |recipe| %>
      <%= link_to recipe_path(recipe.id), class: "each-recipe-link" do %>
      <div class="each-recipe-c">
      <div class="">
        <h3><%= recipe.name %></h3>
        
        <% if can? :destroy, recipe %>
        <%= button_to "Remove", recipe_path(recipe.id ), :method => :delete, class: "recipe-dlt-btn" %> 
        <% end %>

      </div>
      <div class="recipes-desc">
        <p><%= recipe.description %></p>
      </div>
      </div>
      <% end %>
  <% end %>
  </div>

</div>

app/views/recipes/new.html.erb
<div class="recipes-new-c">
  <h3 class='recipes-new-h3'> Add Recipe</h3>
  <%= form_with url: recipes_path, scope: :recipe do |form| %>
    <div class="foods-new-div">
    <%= form.label :Name, class:"form-label" %><br>
    <%= form.text_field :name, class: 'form-control', require: true %>
    </div>

    <div class="foods-new-div">
    <%= form.label :Preparation_Time, class:"form-label" %><br>
    <%= form.text_field :preparation_time, class: 'form-control', require: true %>
    </div>

    <div class="foods-new-div">
    <%= form.label :Cooking_Time, class:"form-label" %><br>
    <%= form.text_field :cooking_time, class: 'form-control', require: true %>
    </div>
    
    <div class="foods-new-div">
    <%= form.label :Description, class:"form-label" %><br>
    <%= form.text_area :description, class: 'form-control', require: true %>
    </div>

    <%= form.submit "Submit", class: "foods-new-btn" %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="recipe-show-c">
  <h2 class="recipe-show-h2"><%= @recipe.name %></h2>
 
  <div class="d-flex recipe-show-d1">
    <p class="flex-grow-1 recipe-show-prep-t">Preparation time: <%= @recipe.preparation_time %></p>
    <p class="recipe-show-publcT">Public</p>

    <% if current_user.id == @recipe.user.id %> 
    <%= button_to recipe_path(@recipe.id), :method => :patch, class: "align-self-end public-btn" do %>
      <% if @recipe.public %>
        <i class="fa fa-toggle-on" style="font-size:48px;color:seagreen"></i>
      <% else %>
        <i class="fa fa-toggle-off" style="font-size:48px;color:seagreen"></i>
      <% end %>
    <% end %>
    <% end %>
  </div>


     <p class="show-cook-time">Cooking time: <%= @recipe.cooking_time %></p>
     <p class="show-steps">Steps goes here...</p>

   <div class="d-flex justify-content-between">
   <% if current_user.id == @recipe.user.id %> 
   <button class='shopping-list-btn'>
   <%= link_to 'Generate shooping list', shopping_list_index_path, class: "shopping-list-btn-t" %>
 </button> 
   <button class='add-ingre-btn'>
   <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe.id), class: "add-ingre-btn-t" %>
 </button> 
 <% end %>
   </div>

   <table class="table m-5">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
    <% @recipe.recipe_foods.each do |recipe_food| %>
      <tr>
        <th scope="row"><%= recipe_food.food.name %> </th>
        <td><%= recipe_food.quantity %><%= recipe_food.food.measurement_unit %> </td>
        <td>  $<%= recipe_food.food.price*recipe_food.quantity %></td>
        <td class="show-btns"> 
        <% if can? :destroy, @recipe %>
        <%= link_to "Modify", edit_recipe_recipe_food_path(@recipe.id, recipe_food.id), class: "show-modify-btn" %> 
          <%= button_to "Remove", recipe_recipe_food_path(@recipe.id, recipe_food.id), :method => :delete, class: "show-dlt-btn" %> 
          <% end %>
        </td>
      </tr>
      <%end %>
   </tbody>
  </table>

</div>