config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # route for home page
  root 'users#index'

  resources :foods, only: [:index, :new, :create, :destroy]

  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  
  resources :public_recipes, only: [:index]

  resources :shopping_list, only: [:index]
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, length: { in: 1..50 }
  validates :measurement_unit, presence: true, length: { in: 1..20 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    redirect_to foods_path, flash: { alert: 'Please sign up or login!' } unless current_user

    @food = Food.new
  end

  def create
    @new_food = current_user.foods.new(food_params)
    if @new_food.save
      redirect_to foods_path, flash: { alert: 'Your food is saved' }
    else
      redirect_to new_food_path, flash: { alert: 'Could not save your food' }
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy!
    flash[:notice] = 'You have deleted the food!'
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<div class="foods-c">  
<h3 class="foods-h3">All Foods</h1>
  <div class="d-flex justify-content-end m-3">
       <button class='food-new-btn'>
      <%= link_to 'Add new food', new_food_path, class: "food-new-btn-t" %>
    </button> 
  </div>
  <table class="table m-3">
    <thead>
        <tr>
        <th scope="col">Food</th>
        <th scope="col">Measurement Unit</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
        <th scope="row"> <%= food.name %> </th>
        <td> <%= food.measurement_unit %> </td>
        <td>$<%= food.price %> </td>   
         <td> 
          <% if can? :destroy, food %> 
            <%= button_to "Delete", food_path( food.id ), :method => :delete, class: "food-dlt-btn" %> 
          <% end %>
        </td>     
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class="foods-new-c">
  <h3 class="foods-new-h3"> Add Food</h3>
  <%= form_with url: foods_path, scope: :food do |form| %>
    <div class="foods-new-div">
    <%= form.label :Name, class:"form-label" %><br>
    <%= form.text_field :name, class: 'form-control', require: true %>
    </div>

    <div class="foods-new-div">
    <%= form.label :Measurement_Unit, class:"form-label" %><br>
    <%= form.text_field :measurement_unit, class: 'form-control', require: true %>
    </div>

    <div class="foods-new-div">
    <%= form.label :Price, class:"form-label" %><br>
    <%= form.number_field :price, class: 'form-control', require: true %>
    </div>

    <%= form.submit "Submit", class: "foods-new-btn" %>
  <% end %>
</div>