config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # route for home page
  root 'users#index'

  resources :foods, only: [:index, :new, :create, :destroy]

  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  
  resources :public_recipes, only: [:index]

  resources :shopping_list, only: [:index]
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 1 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @recipe_id = params[:recipe_id]
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.create(recipe_food_params)
    if @recipe_food.save
      redirect_to recipe_path(params[:recipe_id]), flash: { alert: 'Your food is saved' }
    else
      redirect_to new_recipe_recipe_food_path, flash: { alert: 'Could not save your food' }
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy!
    flash[:notice] = 'You have deleted the recipe food!'
    redirect_to recipe_path(params[:recipe_id])
  end

  def edit
    @recipe_id = params[:recipe_id]
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.update(edit_recipe_food_params)
    flash[:notice] = 'You have updated the recipe food successfully'
    redirect_to recipe_path(params[:recipe_id])
  end

  private

  def edit_recipe_food_params
    params.require(:edit_recipe_food).permit(:quantity, :food_id)
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/edit.html.erb
<div class="recipe-food-edit">
  <h3 class='m-3 recipe-food-new-h3'> Add food to Recipe</h3>
  <%= form_with url: recipe_recipe_food_path, method: :patch, scope: :edit_recipe_food do |form| %>
    <div class="form-div" > -
    <div class="mb-3 col-sm-4">
    <%= form.label :food, class:"form-label" %><br>
    <%= form.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: true} , required: true, class:"form-select" %><br>

    </div>

    <div class="mb-3 col-sm-4">
    <%= form.label :quantity, class:"form-label" %><br>
    <%= form.number_field :quantity ,  class:"form-control" , required: true, placeholder: '1',  min: 1%><br>
    </div>

    <div class="recipe-food-edit-btns">
    <%= form.submit "Update", class:"btn btn-primary form-control2" %>
    <%=link_to 'Back', recipe_path(@recipe_id), class:"btn btn-primary form-control2"%>
    </div>
    </div>
<%end%>
</div>

app/views/recipe_foods/new.html.erb
<div class="recipe-food-new">
  <h3 class='m-3 recipe-food-new-h3'> Add food to Recipe</h3>
  <%= form_with url: recipe_recipe_foods_path, scope: :recipe_food do |form| %>
    <div class="form-div" > -
    <div class="mb-3 col-sm-4">
    <%= form.label :food, class:"form-label" %><br>
    <%= form.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: true} , class:"form-select" %><br>

    </div>

    <div class="mb-3 col-sm-4">
    <%= form.label :quantity, class:"form-label" %><br>
    <%= form.number_field :quantity ,  class:"form-control" , required: true, placeholder: '1',  min: 1%><br>
    </div>

    <div class="recipe-food-btns">
    <%= form.submit "Add", class:"btn btn-primary form-control2" %>
        <%=link_to 'Back', recipe_path(@recipe_id), class:"btn btn-primary form-control2"%>
  </div>
<%end%>

</div>