config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # route for home page
  root 'users#index'

  resources :foods, only: [:index, :new, :create, :destroy]

  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  
  resources :public_recipes, only: [:index]

  resources :shopping_list, only: [:index]
end

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <a class="home" href="/">Best Recipe App</a>
  <div class="menu">
    <%= link_to "Foods", foods_path, class: "nav-link" %>
    <%= link_to 'Recipes', recipes_path, class: "nav-link" %> 
    <%= link_to 'Public Recipes', public_recipes_path, class: "nav-link" %>
    <%= link_to 'Shopping List', shopping_list_index_path, class: "nav-link" %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BestRecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>   
  </head>

  <body>
   <%= render "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="max-w-6xl pt-4 mx-auto">
      <%= yield %>
    </div>                                                                        
    <div class="session-msg"> 
      <% if user_signed_in? %>       
        Signed in as <%= current_user.name %>. This cannot be cheese?&nbsp; <%= button_to "Log out", destroy_user_session_path, :method => :delete, class: "sign-out-btn" %> 
      <% else %>       
        <%= link_to 'Register', new_user_registration_path, class: "sign-out-btn" %> &nbsp;or&nbsp; <%= link_to 'Sign in', new_user_session_path, class: "sign-out-btn"%> 
      <% end %> 
    </div> 
  </body>
</html>